---
layout: 12pt
header-includes:
   - \usepackage{lineno}
   - \linenumbers
   - \usepackage{setspace}
   - \doublespacing

## rmarkdown render options
output:
  pdf_document:
    fig_caption: true
    keep_tex: false
fontsize: 12pt
geometry: margin=1in

---

Environmental responses consistently, but not completely, synchronize population dynamics of co-occuring grassland species?
========================================================================================

### Andrew T. Tredennick and ... and ...
Introduction
------------
Asynchrony in population dynamics 

The Neutral Expectation
-----------------------
Before calculating and interpreting community synchrony, it is helpful to explicitly define the null hypothesis against which observed synchrony will be compared. Unlike some previous studies, we start with the neutral expectation that coexisting species within the same trophic level should fluctuate in perfect synchrony.

Previous work to assess the ubiquity of asynchronous or compensatory dynamics (e.g., Houlahan) in natural communities has suffered from three flaws: (1) they lacked a synchrony metric that does not rely on pair-wise comparisons (see Brown et al. 2004 for critique summed negative covariances), (2) they compared observed synchrony to the biologically unrealistic null hypothesis of independent species fluctuations, and (3) they used population size, or proxies thereof, to calculate synchrony rather than per capita population growth rates that reflect the environmental forces governing population dynamics from one generation to the next. 

Methods
-------
We built environmentally and demographically stochastic multi-species integral projection models (IPMs) to simulate species' dynamics through time. The IPMs are based on vital rate regressions for survival, growth, and recruitment (Chu and Adler 2015). Environmental stochasticity is incorporated by fitting random year effects for the intercept of all regressions and on the plant size effect in the survival and growth regressions. Thus, for a fluctuating environment we can randomly draw year-specific regressions for each time-step of the IPM. Alternatively, to simulate the community in a constant environment we can use the mean regressions for each species. We incorporate demographic stochasticity in the IPM by making survival a binomial process (see Vindenes et al. 2011). We can remove demographic stochaticity by treating survival as a continuous rather than binomial process, as is traditionally done with IPMs (e.g., Rees and Ellner 2014).

To determine the (de)synchronizing effects of demographic stochasticity and species' responses to the environment we simulated communities using the IPM under three scenarios: (1) demographic and environmental stochasticity included, (2) demographic stochasticity removed, and (3) environmental stochasticity removed. We ran simulations for 2,500 time steps and calculated $\phi_r$ using the final 1,000 time steps. For each of our study sites we then calculated $\Delta(\phi)$, the difference between either scenarios 2 or 3 and the unperturbed scenario 1. The sign and magnitude of $\Delta(\phi)$ indicates the (de)synchronizing effect of removing either demographic or environmental stochasticity.

Results and Discussion
-------
Synchrony of per capita growth rates among species in each community were in the range ## - ## with an average synchrony of ## (Table #). If our null expectation had been independent fluctuations, then we would conclude that these communities are far from exhibiting asynchronous dynamics. However, based on neutral theory, we expected the species to fluctuate in perfect synchrony. Thus, our results show that these communities exhibit weak asynchrony since any asynchrony in temporal dynamics drives $\phi_r$ away from zero.  

```{r, echo=FALSE, include=TRUE, fig.height=4, fig.width=5.5, fig.cap="Effect of removing demographic and environmental stochasticity on the synchrony of population dynamics."}
## PLOT FROM 3-25-2015
library(ggplot2)
synch_data <- data.frame(site = rep(c("Idaho", "Kansas"), each=3),
                         simulation = rep(c("Both", "Demo only", "Env only"), times=2),
                         synchrony = c(0.6,0.49,0.58,
                                       0.61,0.51,0.65))
synch_diff <- data.frame(Site = rep(c("Idaho", "Kansas"), each=2),
                         Perturbation = rep(c("Env. Stoch. Removed", "Dem. Stoch. Removed"), times=2),
                         synchrony = c(-0.11, -0.02,
                                       -0.1, 0.04))

ggplot(synch_diff)+
  geom_bar(aes(x=Site, y=synchrony, fill=Perturbation), 
           stat="identity", position='dodge', size=2)+
  geom_hline(aes(yintercept=0))+
  ylab("Perturbed Synchrony - Unperturbed Synchrony")+
  xlab("Site")+
  theme_bw()+
  scale_fill_manual(values=c("grey35", "darkorange"))
#   theme(axis.title.x=element_text(size=14, family="Times New Roman"),
#         axis.title.y=element_text(size=14, family="Times New Roman"),
#         axis.text=element_text(size=12, family="Times New Roman"),
#         legend.text=element_text(size=14, family="Times New Roman"), 
#         legend.title=element_blank())
```


